language: clojure

branches:
    only: source

script: lein cljsbuild once min

deploy:
    provider: pages
    skip_cleanup: true
    target_branch: master
    github_token: $GH_TOKEN
    local_dir: "resources/public"
    on:
        branch: source
