language: clojure

branches:
    only: source

script: lein cljsbuild once min

before_deploy: bash ci/post_build.sh

deploy:
    provider: pages
    skip_cleanup: true
    target_branch: master
    github_token: $GH_TOKEN
    local_dir: www
    on:
        branch: source
